stages:
  - build
  - test
  - publish

build:
  stage: build
  tags:
    - clang
    - make
  script:
    - make static -j $(nproc)
  artifacts:
    expire_in: 1 week
    paths:
      - libo2s.a
      - include/

test:
  stage: test
  tags:
    - conan
    - clang
    - make
  dependencies:
    - build
  script:
    - conan install test --build=missing
    - make -C test conan_build -j $(nproc)
    - make -C test run

coverage:
  stage: test
  tags:
    - nix
  script:
    - nix develop --command bash coverage.sh llvm non-interactive
    - nix-shell --packages python311Packages.lcov_cobertura --command "lcov_cobertura lcov.info"
  coverage: '/lines[.]+:\s\d+[.]\d+%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

publish:
  stage: publish
  tags:
    - conan1
  only:
    refs:
      - tags
  script:
    - conan remote add gitlab ${CI_API_V4_URL}/packages/conan
    - export PACKAGE="libo2s/${CI_COMMIT_TAG}@${CI_PROJECT_NAMESPACE}+${CI_PROJECT_NAME}/gitlab"
    - conan create . $PACKAGE
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload $PACKAGE --remote gitlab

  
