check version:
  stage: .pre
  tags:
    - linux
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - test "$CI_COMMIT_TAG" = "$(cat version.txt)"

build:
  stage: build
  tags:
    - nix
  script:
    - "nix build .#libo2s.out"
    - "nix build .#libo2s.ci"
    - cp result-ci/report.xml .
  artifacts:
    reports:
      junit: report.xml

coverage:
  stage: build
  tags:
    - nix
  script:
    - "nix build .#libo2s-cov"
    - cp result/test_libo2s.exe/cobertura.xml .
    - sed --regexp-extended "s|<source>[^<>]+</source>|<source>${CI_PROJECT_DIR}/src</source>|" -i cobertura.xml
    - "awk -F: '$1~/percent_covered/ { print }' result/test_libo2s.exe/coverage.json"
  coverage: '/"percent_covered":\s*"[0-9.]+"/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

code_quality:
  tags:
    - nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - 'git clone https://github.com/Orolia2s/qualamity.git'
    - 'PYTHONPATH=qualamity nix develop ./qualamity -c python -m qualamity src include -f csv > qualimetry.csv'
  artifacts:
    paths:
      - qualimetry.csv
    expire_in: 1 week

publish:
  stage: deploy
  tags:
    - conan1
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - conan remote add gitlab ${CI_API_V4_URL}/packages/conan
    - export PACKAGE="libo2s/${CI_COMMIT_TAG}@${CI_PROJECT_NAMESPACE}+${CI_PROJECT_NAME}/gitlab"
    - conan create . $PACKAGE
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload $PACKAGE --remote gitlab

pages:
  stage: deploy
  tags:
    - nix
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - "nix build .#libo2s-doc"
    - cp -r result/share/doc/html public
  artifacts:
    paths:
      - public
