stages:
  - build
  - test
  - publish

check version:
  stage: .pre
  tags:
    - linux
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - test "$CI_COMMIT_TAG" = "$(cat version.txt)"

build:
  stage: build
  tags:
    - nix
  script:
    - "nix build .#libo2s.out"
    - "nix build .#libo2s.ci"
    - cp result-ci/report.xml .
  artifacts:
    reports:
      junit: report.xml

coverage:
  stage: test
  tags:
    - nix
  script:
    - "nix build .#libo2s-cov"
    - cp result/test_libo2s.exe/cobertura.xml .
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

publish:
  stage: publish
  tags:
    - conan1
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - conan remote add gitlab ${CI_API_V4_URL}/packages/conan
    - export PACKAGE="libo2s/${CI_COMMIT_TAG}@${CI_PROJECT_NAMESPACE}+${CI_PROJECT_NAME}/gitlab"
    - conan create . $PACKAGE
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload $PACKAGE --remote gitlab

pages:
  stage: publish
  tags:
    - nix
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - "nix build .#libo2s-doc"
    - cp -r result/share/doc/html public
  artifacts:
    paths:
      - public
