stages:
  - build
  - test
  - publish

build:
  stage: build
  tags:
    - clang
    - make
  script:
    - make static -j $(nproc)
  artifacts:
    expire_in: 1 week
    paths:
      - libo2s.a
      - include/

test:
  stage: test
  tags:
    - conan
    - clang
    - make
  dependencies:
    - build
  script:
    - conan install test --build=missing
    - make -C test conan_build -j $(nproc)
    - make -C test run

publish:
  stage: publish
  image: registry.orolia.com/mirrors/public-images/conan-runner:1.53.0
  only:
    refs:
      - tags
  script:
    - conan remote add gitlab ${CI_API_V4_URL}/packages/conan
    - export VERSION=$(make version)
    - export PACKAGE="libo2s/$VERSION@orolia2s+libo2s/${CI_COMMIT_BRANCH}"
    - conan create . $PACKAGE
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload $PACKAGE --remote gitlab
