#pragma once

/* Version for gcc < 8 or clang < 12, using a GNU extension */
// #define O2SPP_ARGCNT1(...) O2SPP_ARGCNT2(IGNORED, ##__VA_ARGS__, O2SPP_ARGCNT4)
// #define O2SPP_ARGCNT4 39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0

#define O2SPP_ARGCNT1(...) O2SPP_ARGCNT2(__VA_ARGS__ __VA_OPT__(,) O2SPP_ARGCNT4)
#define O2SPP_ARGCNT2(...) O2SPP_ARGCNT3(__VA_ARGS__)
#define O2SPP_ARGCNT3(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN, n, ...) n
#define O2SPP_ARGCNT4 40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0

#define FNV1A_N(...) \
	LIBO2S_PREPRO_CONCAT(FNV1A_, LIBO2S_PREPRO_ARGUMENT_COUNT(__VA_ARGS__))(__VA_ARGS__)

#define FNV1A_F    16777619U
#define FNV1A_0()  2166136261U
#define FNV1A_1(A) ((A ^ FNV1A_0()) * FNV1A_F)

#define FNV1A_2(AA,AB) \
	((AB ^ FNV1A_1(AA)) * FNV1A_F)
#define FNV1A_3(AA,AB,AC) \
	((AC ^ FNV1A_2(AA,AB)) * FNV1A_F)
#define FNV1A_4(AA,AB,AC,AD) \
	((AD ^ FNV1A_3(AA,AB,AC)) * FNV1A_F)
#define FNV1A_5(AA,AB,AC,AD,AE) \
	((AE ^ FNV1A_4(AA,AB,AC,AD)) * FNV1A_F)
#define FNV1A_6(AA,AB,AC,AD,AE,AF) \
	((AF ^ FNV1A_5(AA,AB,AC,AD,AE)) * FNV1A_F)
#define FNV1A_7(AA,AB,AC,AD,AE,AF,AG) \
	((AG ^ FNV1A_6(AA,AB,AC,AD,AE,AF)) * FNV1A_F)
#define FNV1A_8(AA,AB,AC,AD,AE,AF,AG,AH) \
	((AH ^ FNV1A_7(AA,AB,AC,AD,AE,AF,AG)) * FNV1A_F)
#define FNV1A_9(AA,AB,AC,AD,AE,AF,AG,AH,AI) \
	((AI ^ FNV1A_8(AA,AB,AC,AD,AE,AF,AG,AH)) * FNV1A_F)
#define FNV1A_10(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ) \
	((AJ ^ FNV1A_9(AA,AB,AC,AD,AE,AF,AG,AH,AI)) * FNV1A_F)
#define FNV1A_11(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK) \
	((AK ^ FNV1A_10(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ)) * FNV1A_F)
#define FNV1A_12(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL) \
	((AL ^ FNV1A_11(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK)) * FNV1A_F)
#define FNV1A_13(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM) \
	((AM ^ FNV1A_12(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL)) * FNV1A_F)
#define FNV1A_14(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN) \
	((AN ^ FNV1A_13(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM)) * FNV1A_F)
#define FNV1A_15(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO) \
	((AO ^ FNV1A_14(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN)) * FNV1A_F)
#define FNV1A_16(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP) \
	((AP ^ FNV1A_15(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO)) * FNV1A_F)
#define FNV1A_17(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ) \
	((AQ ^ FNV1A_16(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP)) * FNV1A_F)
#define FNV1A_18(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR) \
	((AR ^ FNV1A_17(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ)) * FNV1A_F)
#define FNV1A_19(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS) \
	((AS ^ FNV1A_18(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR)) * FNV1A_F)
#define FNV1A_20(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT) \
	((AT ^ FNV1A_19(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS)) * FNV1A_F)
#define FNV1A_21(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU) \
	((AU ^ FNV1A_20(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT)) * FNV1A_F)
#define FNV1A_22(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV) \
	((AV ^ FNV1A_21(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU)) * FNV1A_F)
#define FNV1A_23(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW) \
	((AW ^ FNV1A_22(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV)) * FNV1A_F)
#define FNV1A_24(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX) \
	((AX ^ FNV1A_23(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW)) * FNV1A_F)
#define FNV1A_25(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY) \
	((AY ^ FNV1A_24(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX)) * FNV1A_F)
#define FNV1A_26(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ) \
	((AZ ^ FNV1A_25(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY)) * FNV1A_F)
#define FNV1A_27(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA) \
	((BA ^ FNV1A_26(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ)) * FNV1A_F)
#define FNV1A_28(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB) \
	((BB ^ FNV1A_27(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA)) * FNV1A_F)
#define FNV1A_29(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC) \
	((BC ^ FNV1A_28(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB)) * FNV1A_F)
#define FNV1A_30(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD) \
	((BD ^ FNV1A_29(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC)) * FNV1A_F)
#define FNV1A_31(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE) \
	((BE ^ FNV1A_30(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD)) * FNV1A_F)
#define FNV1A_32(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF) \
	((BF ^ FNV1A_31(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE)) * FNV1A_F)
#define FNV1A_33(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG) \
	((BG ^ FNV1A_32(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF)) * FNV1A_F)
#define FNV1A_34(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH) \
	((BH ^ FNV1A_33(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG)) * FNV1A_F)
#define FNV1A_35(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI) \
	((BI ^ FNV1A_34(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH)) * FNV1A_F)
#define FNV1A_36(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ) \
	((BJ ^ FNV1A_35(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI)) * FNV1A_F)
#define FNV1A_37(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK) \
	((BK ^ FNV1A_36(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ)) * FNV1A_F)
#define FNV1A_38(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL) \
	((BL ^ FNV1A_37(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK)) * FNV1A_F)
#define FNV1A_39(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM) \
	((BM ^ FNV1A_38(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL)) * FNV1A_F)
#define FNV1A_40(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN) \
	((BN ^ FNV1A_39(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM)) * FNV1A_F)
